/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['hello'],
//     },
//   ],
//    */
// };

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'doc',
      label: 'Home',
      id: 'intro'
    },
    {
      type: 'link',
      label: 'Lib',
      href: '/docs/plouffe_lib/configuration'
    },
    {
      type: 'link',
      label: 'Doorlock',
      href: '/docs/plouffe_doorlock/configuration'
    },
    {
      type: 'link',
      label: 'Shops Robbery',
      href: '/docs/plouffe_shopsrobbery/configuration'
    },
    {
      type: 'link',
      label: 'Fleeca Heist',
      href: '/docs/plouffe_fleeca/configuration'
    },
    {
      type: 'link',
      label: 'Paleto Bank Heist',
      href: '/docs/plouffe_paletobank/configuration'
    },
    {
      type: 'link',
      label: 'Vangelico Heist',
      href: '/docs/plouffe_vangelico/configuration'
    },
    {
      type: 'link',
      label: 'Train Heist',
      href: '/docs/plouffe_trainrobbery/configuration'
    },
    {
      type: 'link',
      label: 'Cayo Perico Heist',
      href: '/docs/plouffe_cayorobbery/configuration'
    },
    {
      type: 'link',
      label: 'Drugs',
      href: '/docs/plouffe_drugs/configuration'
    },
    {
      type: 'link',
      label: 'Weapons',
      href: '/docs/plouffe_weapons/configuration'
    },
    {
      type: 'link',
      label: 'Jail',
      href: '/docs/plouffe_jail/configuration'
    }
  ],
  plouffe_lib: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs/intro'
    },
    {
      type: 'category',
      label: 'Plouffe lib',
      link: {
        type: 'generated-index',
        title: 'Plouffe lib',
        description: 'Script used as a depencies for most of my other scripts'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plouffe_lib'
        }
      ]
    }
  ],
  plouffe_doorlock: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs/intro'
    },
    {
      type: 'category',
      label: 'Doorlock',
      link: {
        type: 'generated-index',
        title: 'Doorlock',
        description: 'Doorlock can be used as stand alone but is most used as a depencie'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plouffe_doorlock'
        }
      ]
    }
  ],
  plouffe_fleeca: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs/intro'
    },
    {
      type: 'category',
      label: 'Fleeca Heist',
      link: {
        type: 'generated-index',
        title: 'Fleeca Heist',
        description: 'Fleeca Heist'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plouffe_fleeca'
        }
      ]
    }
  ],
  plouffe_paletobank: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs/intro'
    },
    {
      type: 'category',
      label: 'Paleto Bank Heist',
      link: {
        type: 'generated-index',
        title: 'Paleto Bank Heist',
        description: 'Paleto Bank Heist'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plouffe_paletobank'
        }
      ]
    }
  ],
  plouffe_shopsrobbery: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs/intro'
    },
    {
      type: 'category',
      label: 'Shops Robbery',
      link: {
        type: 'generated-index',
        title: 'Shops Robbery',
        description: 'Shops Robbery'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plouffe_shopsrobbery'
        }
      ]
    }
  ],
  plouffe_vangelico: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs/intro'
    },
    {
      type: 'category',
      label: 'Vangelico Heist',
      link: {
        type: 'generated-index',
        title: 'Vangelico Heist',
        description: 'Vangelico Heist'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plouffe_vangelico'
        }
      ]
    }
  ],
  plouffe_trainrobbery: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs/intro'
    },
    {
      type: 'category',
      label: 'Train Heist',
      link: {
        type: 'generated-index',
        title: 'Train Heist',
        description: 'Train Heist'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plouffe_trainrobbery'
        }
      ]
    }
  ],
  plouffe_cayorobbery: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs/intro'
    },
    {
      type: 'category',
      label: 'Cayo Perico Heist',
      link: {
        type: 'generated-index',
        title: 'Cayo Perico Heist',
        description: 'Cayo Perico Heist'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plouffe_cayorobbery'
        }
      ]
    }
  ],
  plouffe_drugs: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs/intro'
    },
    {
      type: 'category',
      label: 'Drugs',
      link: {
        type: 'generated-index',
        title: 'Drugs',
        description: 'Drug fabrication/harvesting script with effects'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plouffe_drugs'
        }
      ]
    }
  ],
  plouffe_weapons: [
    {
      type: 'link',
      label: '← Home',
      href: '/docs/intro'
    },
    {
      type: 'category',
      label: 'Weapons',
      link: {
        type: 'generated-index',
        title: 'Weapons',
        description: 'All sorts of weapons related functions'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plouffe_weapons'
        }
      ]
    }
  ],
};

module.exports = sidebars;
